version: '3'

services:
  app:
    build:
      context: ./
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - /home/mpdev/projects/app
    tty: true
    ports:
      - "3000:3000"
    command: ["node", "index.js"]
    depends_on: 
      - db

  db:
    image: mysql:5.7
    command: [--innodb-use-native-aio=0, --max_allowed_packet=32505856]
    container_name: db
    restart: always 
    tty: true
    volumes:
      - /var/lib/mysql 
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: mpdeving/nginx:prod
    container_name: nginx

    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
    - app

networks:
  node-network:
    driver: bridge
    